#!/usr/bin/env python3
"""
Zoho OAuth Setup Redirect URI Test
Tests the exact redirect URI being generated by the Zoho OAuth setup endpoint
"""

import requests
import json
import sys
from urllib.parse import urlparse, parse_qs, unquote
from datetime import datetime

# Configuration
BASE_URL = "https://fintech-collector.preview.emergentagent.com"
API_BASE = f"{BASE_URL}/api"

# Test user credentials
TEST_USER = {
    "name": "OAuth Test User",
    "email": "oauthtest@test.com", 
    "password": "testpass123"
}

# User-provided Zoho credentials from review request
ZOHO_CREDENTIALS = {
    "client_id": "1000.OH8JNIK1UP8VEGHLM6QN4BC6CM801K",
    "client_secret": "c7ff157ccf95db7751ed218370973cf86db0477597"
}

class ZohoOAuthRedirectTester:
    def __init__(self):
        self.auth_token = None
        
    def make_request(self, method, endpoint, data=None, headers=None):
        """Make HTTP request with error handling"""
        url = f"{API_BASE}{endpoint}"
        
        try:
            if headers is None:
                headers = {"Content-Type": "application/json"}
                
            if method.upper() == "GET":
                response = requests.get(url, headers=headers, timeout=30)
            elif method.upper() == "POST":
                response = requests.post(url, json=data, headers=headers, timeout=30)
            else:
                raise ValueError(f"Unsupported method: {method}")
                
            return response
            
        except requests.exceptions.RequestException as e:
            print(f"❌ Request failed for {endpoint}: {str(e)}")
            return None
    
    def setup_test_user(self):
        """Create and login test user"""
        print("🔧 Setting up test user...")
        
        # Try to register user (might already exist)
        response = self.make_request("POST", "/auth/signup", TEST_USER)
        if response and response.status_code in [200, 400]:  # 400 if user exists
            print("✅ User registration handled")
        else:
            print("❌ Failed to handle user registration")
            return False
            
        # Login to get auth token
        login_data = {
            "email": TEST_USER["email"],
            "password": TEST_USER["password"]
        }
        
        response = self.make_request("POST", "/auth/login", login_data)
        
        if response and response.status_code == 200:
            try:
                data = response.json()
                if data.get("success") and data.get("token"):
                    self.auth_token = data["token"]
                    print(f"✅ Login successful, token obtained")
                    return True
                else:
                    print("❌ Login response missing success or token")
            except json.JSONDecodeError:
                print("❌ Invalid JSON response from login")
        else:
            print(f"❌ Login failed with status {response.status_code if response else 'None'}")
            
        return False
    
    def test_zoho_oauth_redirect_uri(self):
        """Test Zoho OAuth setup and extract redirect URI"""
        print("\n🔍 Testing Zoho OAuth Setup Endpoint...")
        print("=" * 60)
        
        if not self.auth_token:
            print("❌ No auth token available")
            return False
            
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.auth_token}"
        }
        
        # Send POST request with user-provided credentials
        print(f"📤 Sending POST request to /api/integrations/zoho/user-oauth-setup")
        print(f"   Client ID: {ZOHO_CREDENTIALS['client_id']}")
        print(f"   Client Secret: {ZOHO_CREDENTIALS['client_secret'][:10]}...")
        
        response = self.make_request("POST", "/integrations/zoho/user-oauth-setup", ZOHO_CREDENTIALS, headers)
        
        if response is None:
            print("❌ Request failed - connection error")
            return False
            
        print(f"📥 Response Status: {response.status_code}")
        
        if response.status_code == 200:
            try:
                data = response.json()
                
                if "auth_url" in data and "state" in data:
                    auth_url = data["auth_url"]
                    state = data["state"]
                    
                    print("\n✅ SUCCESS: OAuth setup endpoint working")
                    print("=" * 60)
                    
                    # Display full auth URL
                    print("🔗 FULL AUTH URL:")
                    print(f"   {auth_url}")
                    print()
                    
                    # Parse the URL to extract parameters
                    parsed_url = urlparse(auth_url)
                    query_params = parse_qs(parsed_url.query)
                    
                    print("📋 OAUTH PARAMETERS:")
                    for param, values in query_params.items():
                        value = values[0] if values else ""
                        if param == "redirect_uri":
                            decoded_value = unquote(value)
                            print(f"   {param}: {decoded_value}")
                            print(f"   {param} (encoded): {value}")
                        else:
                            print(f"   {param}: {value}")
                    
                    # Extract and verify redirect_uri specifically
                    if "redirect_uri" in query_params:
                        redirect_uri_encoded = query_params["redirect_uri"][0]
                        redirect_uri_decoded = unquote(redirect_uri_encoded)
                        
                        print("\n🎯 REDIRECT URI ANALYSIS:")
                        print("=" * 40)
                        print(f"Encoded:  {redirect_uri_encoded}")
                        print(f"Decoded:  {redirect_uri_decoded}")
                        
                        expected_redirect_uri = "https://fintech-collector.preview.emergentagent.com/zoho/callback"
                        
                        if redirect_uri_decoded == expected_redirect_uri:
                            print(f"Expected: {expected_redirect_uri}")
                            print("✅ REDIRECT URI MATCHES EXPECTED VALUE")
                        else:
                            print(f"Expected: {expected_redirect_uri}")
                            print("❌ REDIRECT URI DOES NOT MATCH EXPECTED VALUE")
                            
                        print(f"\n📊 State Token: {state}")
                        print(f"📊 State Length: {len(state)} characters")
                        
                        return True
                    else:
                        print("❌ redirect_uri parameter not found in auth URL")
                        return False
                        
                else:
                    print("❌ Response missing auth_url or state")
                    print(f"Response data: {data}")
                    return False
                    
            except json.JSONDecodeError:
                print("❌ Invalid JSON response")
                print(f"Response text: {response.text}")
                return False
        else:
            print(f"❌ Request failed with status {response.status_code}")
            try:
                error_data = response.json()
                print(f"Error details: {error_data}")
            except json.JSONDecodeError:
                print(f"Response text: {response.text}")
            return False
    
    def run_test(self):
        """Run the complete test"""
        print("🚀 Starting Zoho OAuth Redirect URI Test")
        print(f"Testing against: {BASE_URL}")
        print("=" * 60)
        
        # Setup test user
        if not self.setup_test_user():
            print("❌ Failed to setup test user")
            return False
        
        # Test OAuth setup endpoint
        success = self.test_zoho_oauth_redirect_uri()
        
        print("\n" + "=" * 60)
        if success:
            print("🎉 TEST COMPLETED SUCCESSFULLY")
            print("✅ Zoho OAuth setup endpoint is working correctly")
            print("✅ Redirect URI is properly configured")
        else:
            print("💥 TEST FAILED")
            print("❌ Issues found with Zoho OAuth setup endpoint")
        
        return success

if __name__ == "__main__":
    tester = ZohoOAuthRedirectTester()
    success = tester.run_test()
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)